name: Sync Fork
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron:  '*/30 * * * *' # every 30 minutes

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.3
        with:
          github_token: ${{ secrets.WORKFLOWS_TOKEN }}
          owner: TryGhost
          base: master
          head: master
          
