name: Sync Fork

on:
  schedule:
    - cron:  "*/5 * * * *" # every 30 minutes

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: TryGhost
          base: master
          head: master

#           git fetch upstream
# git merge upstream/master master
# git rebase upstream/master

# final action leave comment / send comment to slack